### ISSUE TITLE
Gallery: Image size dimension isn't matched as per design including the space gap in between images.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Hollywood-Kitchens#11]
![image](https://cloud.githubusercontent.com/assets/13363508/16574976/eb2ee7ae-42b6-11e6-98f1-7a3199bd215c.png)
![image](https://cloud.githubusercontent.com/assets/13363508/16575032/5596ccd8-42b7-11e6-9f73-41b3bdc4e179.png)

**Comment by titandigitalaus** [comment]
This looks to be fixed.

**Comment by roseliesromeo** [comment]
Inconsistent height of the container.
![image](https://cloud.githubusercontent.com/assets/11186313/17198446/d593fa76-54a7-11e6-8fb2-f2d6adc22f7b.png)

**Comment by roseliesromeo** [comment]
Marked fixed but no changes made.  Have you pushed the changes to stage yet?
Note: Cleared cache already.
![image](https://cloud.githubusercontent.com/assets/11186313/17207224/1e706f98-54e6-11e6-8173-58dc32b16db2.png)

**Comment by euveng** [comment]
Sorry, previously applied the fix for gallery listing but not the single page. This is now fixed.

**Comment by roseliesromeo** [comment]
Div height are still not consistent.
![image](https://cloud.githubusercontent.com/assets/11186313/17281985/4c48a6fc-57d3-11e6-8a1d-881dbe219e87.png)
![image](https://cloud.githubusercontent.com/assets/11186313/17281998/745cb962-57d3-11e6-9ed9-5a4a5bde376f.png)

**Comment by euveng** [comment]
Images need to be at least 400px width and 400px height, so that it can be cropped. I have added upload instructions to the gallery section. Is that ok?

**Comment by roseliesromeo** [comment]
That could help.  But no matter what the size is, it should not the set dimension so as no to break the layout.

Btw, I uploaded image with below 400px width and height and it looks good.
